import React, { FormEvent } from "react";
import Head from "next/head";
import axios from "axios";
import { backendURL } from "../settings";

const Signup: React.FC = () => {
  //TODO : Add useMutation
  async function createUser(e: FormEvent) {
    e.preventDefault();

    //Retrieve Data
    const form: FormData = new FormData(e.target as HTMLFormElement);
    const formData: Object = Object.fromEntries(form.entries());
    const res = await axios.post(backendURL + "/create/user", formData);
    console.log(res);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen absolute w-screen z-20">
        <div className="flex h-screen w-screen">
          {/* Actual thing */}
          <div className="m-auto flex flex-col items-center">
            <h1 className="font-ez text-center text-7xl">Signup</h1>
            <form
              className="w-full max-w-sm mx-auto p-8 rounded-md flex flex-col items-center"
              onSubmit={createUser}
            >
              <div className="mb-4 w-full">
                <label
                  className="block text-gray-700 text-md font-ez mb-2"
                  htmlFor="name"
                >
                  Username 😀😆😅
                </label>
                <input
                  className="font-ez px-3 py-2 border border-gray-300 rounded-md outline-none focus:outline-none focus:border-black transition-all text-sm w-full"
                  type="text"
                  id="name"
                  name="name"
                  placeholder="epic_smasherz"
                />
              </div>

              <div className="mb-4 w-full">
                <label
                  className="block text-gray-700 text-md font-ez mb-2"
                  htmlFor="password"
                >
                  Password 🔑🤐 🔒
                </label>
                <input
                  className="font-ez px-3 py-2 border border-gray-300 rounded-md outline-none focus:outline-none focus:border-black transition-all text-sm w-full"
                  type="password"
                  id="password"
                  name="password"
                  placeholder="fluffykitty@123"
                />
              </div>

              <button className="relative inline-block text-lg group w-40 font-ez scale-90">
                <span className="relative z-10 block px-5 py-3 overflow-hidden font-medium leading-tight text-gray-800 transition-colors duration-300 ease-out border-2 border-gray-900 rounded-lg group-hover:text-white">
                  <span className="absolute inset-0 w-full h-full px-5 py-3 rounded-lg bg-gray-50"></span>
                  <span className="absolute left-0 w-48 h-48 -ml-2 transition-all duration-300 origin-top-right -rotate-90 -translate-x-full translate-y-12 bg-gray-900 group-hover:-rotate-180 ease"></span>
                  <span className="relative">join now</span>
                </span>
              </button>
            </form>
          </div>
        </div>
      </div>
      <div className="h-screen absolute w-screen z-1  background"></div>
    </>
  );
};

export default Signup;
